## 자동차 평가 데이터

In [48]:
# 사용 패키지 불러오기
import pandas as pd # 판다스
from sklearn.model_selection import train_test_split # 훈련/테스트 세트 분리
from sklearn.preprocessing import StandardScaler # 표준화
from sklearn.tree import DecisionTreeClassifier # DT
from sklearn.ensemble import RandomForestClassifier # RF
from sklearn.svm import SVC # SVM
from sklearn.linear_model import LogisticRegression # LR
from sklearn.metrics import accuracy_score # 정확도
from sklearn.neighbors import KNeighborsClassifier # KNN
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, ConfusionMatrixDisplay # 정확도, 혼동행렬
import seaborn as sns # 시본
from sklearn.preprocessing import LabelEncoder # 엔코딩
import matplotlib.pyplot as plt # 맷플롯립

In [23]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow import keras

df = pd.read_csv("/content/drive/MyDrive/car_evaluation.csv")
df

vhigh vhigh.1      2   2.1  small   low  unacc
0     vhigh   vhigh      2     2  small   med  unacc
1     vhigh   vhigh      2     2  small  high  unacc
2     vhigh   vhigh      2     2    med   low  unacc
3     vhigh   vhigh      2     2    med   med  unacc
4     vhigh   vhigh      2     2    med  high  unacc
...     ...     ...    ...   ...    ...   ...    ...
1722    low     low  5more  more    med   med   good
1723    low     low  5more  more    med  high  vgood
1724    low     low  5more  more    big   low  unacc
1725    low     low  5more  more    big   med   good
1726    low     low  5more  more    big  high  vgood

[1727 rows x 7 columns]

In [30]:
df.columns = ['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'output']

In [31]:
df.columns

Index(['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'output'], dtype='object')

In [32]:
df

buying  maint  doors persons lug_boot safety output
0     vhigh  vhigh      2       2    small    med  unacc
1     vhigh  vhigh      2       2    small   high  unacc
2     vhigh  vhigh      2       2      med    low  unacc
3     vhigh  vhigh      2       2      med    med  unacc
4     vhigh  vhigh      2       2      med   high  unacc
...     ...    ...    ...     ...      ...    ...    ...
1722    low    low  5more    more      med    med   good
1723    low    low  5more    more      med   high  vgood
1724    low    low  5more    more      big    low  unacc
1725    low    low  5more    more      big    med   good
1726    low    low  5more    more      big   high  vgood

[1727 rows x 7 columns]

In [33]:
# 결측치 확인
df.isnull().sum()

buying      0
maint       0
doors       0
persons     0
lug_boot    0
safety      0
output      0
dtype: int64

In [34]:
# 레이블 확인
df['output'].value_counts()

output
unacc    1209
acc       384
good       69
vgood      65
Name: count, dtype: int64

In [39]:
# 엔코딩
columns = ['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'output']
label_encoders = {}
for column in columns:
    label_encoders[column] = LabelEncoder()
    df[column] = label_encoders[column].fit_transform(df[column])

In [38]:
df

buying  maint  doors  persons  lug_boot  safety  output
0          3      3      0        0         2       2       2
1          3      3      0        0         2       0       2
2          3      3      0        0         1       1       2
3          3      3      0        0         1       2       2
4          3      3      0        0         1       0       2
...      ...    ...    ...      ...       ...     ...     ...
1722       1      1      3        2         1       2       1
1723       1      1      3        2         1       0       3
1724       1      1      3        2         0       1       2
1725       1      1      3        2         0       2       1
1726       1      1      3        2         0       0       3

[1727 rows x 7 columns]

In [40]:
# X,y 분리
X=df.drop('output', axis=1).values
y=df['output'].values

In [41]:
X

array([[3, 3, 0, 0, 2, 2],
       [3, 3, 0, 0, 2, 0],
       [3, 3, 0, 0, 1, 1],
       ...,
       [1, 1, 3, 2, 0, 1],
       [1, 1, 3, 2, 0, 2],
       [1, 1, 3, 2, 0, 0]])

In [42]:
y

array([2, 2, 2, ..., 2, 1, 3])

In [46]:
# 표준화
scaler = StandardScaler()
X = scaler.fit_transform(X)

# 훈련세트와 테스트세트 분리
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [47]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape,

((1381, 6), (346, 6), (1381,), (346,))

In [49]:
# SVM
print ("==================================")
print (" ACCURACY OF OTHER ML CLASSIFIERS" )
print ("==================================")

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.svm import SVC

clf_svm = SVC(random_state=0)
clf_svm.fit(X_train, y_train)

pred_svm = clf_svm.predict(X_test)

print("\n--- SVM Classifier ---")
print(accuracy_score(y_test, pred_svm))
print(confusion_matrix(y_test, pred_svm))

 ACCURACY OF OTHER ML CLASSIFIERS

--- SVM Classifier ---
0.8786127167630058
[[ 62   1  14   0]
 [  9   4   0   1]
 [ 17   0 222   0]
 [  0   0   0  16]]


In [52]:
# DT
clf_dt = DecisionTreeClassifier(random_state=0)
clf_dt.fit(X_train, y_train)

pred_dt = clf_dt.predict(X_test)

print ("\n--- Decision Tree Classifier ---")
print (accuracy_score(y_test, pred_dt))
print (confusion_matrix(y_test, pred_dt))


--- Decision Tree Classifier ---
0.976878612716763
[[ 74   0   3   0]
 [  0  12   0   2]
 [  0   0 239   0]
 [  3   0   0  13]]


In [53]:
# RF
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

print ("\n--- Radom Forest ---")
rf_clf = RandomForestClassifier(random_state=0)
rf_clf.fit(X_train, y_train)
pred = rf_clf.predict(X_test)
print(accuracy_score(y_test,pred))
print (confusion_matrix(y_test, pred))


--- Radom Forest ---
0.9739884393063584
[[ 72   1   4   0]
 [  1  10   0   3]
 [  0   0 239   0]
 [  0   0   0  16]]


In [65]:
# y : bmi
url = 'https://raw.githubusercontent.com/MyungKyuYi/AI-class/main/diabetes.csv'
data = pd.read_csv(url)

## 당뇨병 데이터(Regression)

In [73]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR

In [66]:
data

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [70]:
# X,y 분리
X = data.drop(columns=['Outcome', 'BMI'])
y = data['BMI'].values

In [69]:
# 훈련세트, 테스트세트 분리
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(614, 7) (614,)
(154, 7) (154,)


In [76]:
# DT
model = DecisionTreeRegressor()
model.fit(X_train, y_train)
dy_preds = model.predict(X_test)
print('평균제곱근오차', mean_squared_error(dy_preds, y_test))

평균제곱근오차 99.4692857142857


In [79]:
# RFR
model = RandomForestRegressor()
model.fit(X_train, y_train)
dy_preds = model.predict(X_test)
print('평균제곱근오차', mean_squared_error(dy_preds, y_test))

평균제곱근오차 48.802420876623394


In [80]:
# SVR
model = SVR()
model.fit(X_train, y_train)
dy_preds = model.predict(X_test)
print('평균제곱근오차', mean_squared_error(dy_preds, y_test))

평균제곱근오차 49.87870996805965
