## **1. 당뇨병 데이터 딥러닝 분류/회귀**

In [66]:
import pandas as pd # 판다스
from sklearn.model_selection import train_test_split # 훈련/테스트 세트 분리
from sklearn.preprocessing import StandardScaler # 표준화
from sklearn.tree import DecisionTreeClassifier # DT
from sklearn.ensemble import RandomForestClassifier # RF
from sklearn.svm import SVC # SVM
from sklearn.linear_model import LogisticRegression # LR
from sklearn.metrics import accuracy_score # 정확도
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder # 엔코딩
from sklearn.metrics import classification_report,confusion_matrix

In [4]:
df1 = pd.read_csv("C:/Users/samsung-user/OneDrive/바탕 화면/인공지능개론/5주차/diabetes.csv")

In [5]:
df1.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [6]:
df1.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [8]:
# 결측치 확인
df1.isnull().sum() 

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

### **1-1. 분류**

In [7]:
# 레이블 확인
df1['Outcome'].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [56]:
X=df1.drop('Outcome',axis=1)
X.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  
0                     0.627   50  
1                     0.351   31  
2                     0.672   32  
3                     0.167   21  
4                     2.288   33

In [57]:
y=df1['Outcome']
y.value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [58]:
Y = pd.get_dummies(y).values

In [59]:
X = X.values

In [60]:
X_train,X_test, y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=0) 

In [61]:
X_train.shape,X_test.shape, y_train.shape, y_test.shape

((614, 8), (154, 8), (614, 2), (154, 2))

In [63]:
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD,Adam

model = Sequential()
model.add(Input(shape=(8,)))
model.add(Dense(16,input_shape=(8,),activation='relu'))
model.add(Dense(32,activation='relu'))
model.add(Dense(16,activation='relu'))
model.add(Dense(2,activation='sigmoid'))


model.compile(optimizer='adam', loss="binary_crossentropy", metrics=['accuracy'])
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_18 (Dense)                     │ (None, 16)                  │             144 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_19 (Dense)                     │ (None, 32)                  │             544 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_20 (Dense)                     │ (None, 16)                  │             528 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_21 (Dense)                     │ (None, 2)                   │              34 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 1,250 (4.88 KB)

 Trainable params: 1,250 (4.88 KB)

 Non-trainable params: 0 (0.00 B)

In [64]:
model_history=model.fit(x=X_train, y=y_train, epochs=30, batch_size=32,validation_split=0.1)
y_pred = model.predict(X_test)

y_test_class = np.argmax(y_test,axis=1)
y_pred_class = np.argmax(y_pred,axis=1)

Epoch 1/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 3s 32ms/step - accuracy: 0.5236 - loss: 6.4184 - val_accuracy: 0.4677 - val_loss: 2.3883
Epoch 2/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.4854 - loss: 2.1694 - val_accuracy: 0.4516 - val_loss: 1.0549
Epoch 3/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.4866 - loss: 1.0281 - val_accuracy: 0.4677 - val_loss: 0.8703
Epoch 4/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.5113 - loss: 0.8215 - val_accuracy: 0.5645 - val_loss: 0.7668
Epoch 5/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5890 - loss: 0.7736 - val_accuracy: 0.7419 - val_loss: 0.7136
Epoch 6/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5820 - loss: 0.7468 - val_accuracy: 0.6935 - val_loss: 0.6919
Epoch 7/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6019 - loss: 0.7230 - val_accuracy: 0.6935 - val_loss: 0.6804
Epoch 8/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.6025 - loss: 0.7117 - val_accuracy: 0.7097 - v

In [65]:
print(classification_report(y_test_class,y_pred_class))
print(confusion_matrix(y_test_class,y_pred_class))

              precision    recall  f1-score   support

           0       0.76      0.93      0.83       107
           1       0.65      0.32      0.43        47

    accuracy                           0.74       154
   macro avg       0.70      0.62      0.63       154
weighted avg       0.72      0.74      0.71       154

[[99  8]
 [32 15]]


### **1-2. 회귀**

In [44]:
X=df1.drop('BMI',axis=1)
X.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin  \
0            6      148             72             35        0   
1            1       85             66             29        0   
2            8      183             64              0        0   
3            1       89             66             23       94   
4            0      137             40             35      168   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [45]:
y=df1['BMI']
y.value_counts()

BMI
32.0    13
31.6    12
31.2    12
0.0     11
32.4    10
        ..
36.7     1
41.8     1
42.6     1
42.8     1
46.3     1
Name: count, Length: 248, dtype: int64

In [46]:
Y = pd.get_dummies(y).values

In [47]:
# 넘파이 변환
X = X.values

In [48]:
X

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

In [49]:
Y

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [50]:
# 훈련/테스트 세트 분리
X_train, X_test, y_train, y_test = train_test_split(X,Y,test_size=0.2,random_state=0)

In [51]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((614, 8), (154, 8), (614, 248), (154, 248))

In [52]:
from keras.models import Sequential
from keras.layers import Input, Dense
from keras.optimizers import SGD, Adam

model = Sequential()

model.add(Input(shape=(8,)))
model.add(Dense(16, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(16, activation='relu'))
model.add(Dense(1))

model.compile(optimizer='rmsprop', loss='mse', metrics=['mse'])
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_10 (Dense)                     │ (None, 16)                  │             144 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_11 (Dense)                     │ (None, 32)                  │             544 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_12 (Dense)                     │ (None, 16)                  │             528 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_13 (Dense)                     │ (None, 1)                   │              17 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 1,233 (4.82 KB)

 Trainable params: 1,233 (4.82 KB)

 Non-trainable params: 0 (0.00 B)

In [53]:
model_history=model.fit(x=X_train, y=y_train, epochs=20, batch_size=32, validation_split=0.1)
y_pred = model.predict(X_test)
y_test_class = np.argmax(y_test,axis=1)
y_pred_class = np.argmax(y_pred,axis=1)

Epoch 1/20
18/18 ━━━━━━━━━━━━━━━━━━━━ 2s 33ms/step - loss: 44.3139 - mse: 44.3139 - val_loss: 4.0693 - val_mse: 4.0693
Epoch 2/20
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 2.7292 - mse: 2.7292 - val_loss: 1.9104 - val_mse: 1.9104
Epoch 3/20
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 1.1334 - mse: 1.1334 - val_loss: 0.6480 - val_mse: 0.6480
Epoch 4/20
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.7930 - mse: 0.7930 - val_loss: 1.7680 - val_mse: 1.7680
Epoch 5/20
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.9819 - mse: 0.9819 - val_loss: 0.8803 - val_mse: 0.8803
Epoch 6/20
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4899 - mse: 0.4899 - val_loss: 0.4971 - val_mse: 0.4971
Epoch 7/20
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.9643 - mse: 0.9643 - val_loss: 1.2936 - val_mse: 1.2936
Epoch 8/20
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.4725 - mse: 0.4725 - val_loss: 0.5753 - val_mse: 0.5753
Epoch 9/20
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.5

In [54]:
model.evaluate(X_test, y_test)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.0583 - mse: 0.0583


[0.059424448758363724, 0.059424448758363724]

## **2. 자동차 평가 데이터 딥러닝 분류**

In [20]:
import tensorflow as tf
from tensorflow import keras

In [21]:
df2 = pd.read_csv("C:/Users/samsung-user/OneDrive/바탕 화면/인공지능개론/5주차/car_evaluation.csv")

In [23]:
df2.head()

vhigh vhigh.1  2 2.1  small   low  unacc
0  vhigh   vhigh  2   2  small   med  unacc
1  vhigh   vhigh  2   2  small  high  unacc
2  vhigh   vhigh  2   2    med   low  unacc
3  vhigh   vhigh  2   2    med   med  unacc
4  vhigh   vhigh  2   2    med  high  unacc

In [24]:
df2.columns=['price', 'maint', 'doors', 'persons', 'lug_capacity', 'safety', 'output']

In [25]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1727 entries, 0 to 1726
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   price         1727 non-null   object
 1   maint         1727 non-null   object
 2   doors         1727 non-null   object
 3   persons       1727 non-null   object
 4   lug_capacity  1727 non-null   object
 5   safety        1727 non-null   object
 6   output        1727 non-null   object
dtypes: object(7)
memory usage: 94.6+ KB


In [26]:
df2.isnull().sum()

price           0
maint           0
doors           0
persons         0
lug_capacity    0
safety          0
output          0
dtype: int64

In [29]:
# 원-핫인코딩
columns = ['price', 'maint', 'doors', 'persons', 'lug_capacity', 'safety', 'output']
label_encoders = {}
for column in columns:
    label_encoders[column] = LabelEncoder()
    df2[column] = label_encoders[column].fit_transform(df2[column])

In [30]:
# 훈련 세트 & 테스트 세트 분할 (8:2)
X = df2.drop('output', axis=1).values
y = df2['output'].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [31]:
# 표준화
scaler = StandardScaler()
X = scaler.fit_transform(X)

# 훈련/테스트 세트 분리
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)     

In [32]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((1381, 6), (346, 6), (1381,), (346,))

In [33]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.utils import to_categorical
import numpy as np

# y 데이터를 one-hot 인코딩
y_train_cat = to_categorical(y_train)
y_test_cat = to_categorical(y_test)

# 모델 구성
model = Sequential()
model.add(Input(shape=(6,))) 
model.add(Dense(6, activation='relu'))
model.add(Dense(4, activation='softmax'))  # ✅ softmax 사용

# 모델 컴파일
model.compile(optimizer=Adam(learning_rate=0.04), 
              loss='categorical_crossentropy', 
              metrics=['accuracy'])

# 모델 요약 출력
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_4 (Dense)                      │ (None, 6)                   │              42 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_5 (Dense)                      │ (None, 4)                   │              28 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 70 (280.00 B)

 Trainable params: 70 (280.00 B)

 Non-trainable params: 0 (0.00 B)

In [35]:
# 모델 학습
model_history = model.fit(x=X_train, y=y_train_cat, 
                          epochs=30, batch_size=32, 
                          validation_data=(X_test, y_test_cat))

# 예측
y_pred = model.predict(X_test)

# 클래스 추출
y_test_class = np.argmax(y_test_cat, axis=1)
y_pred_class = np.argmax(y_pred, axis=1)

Epoch 1/30
44/44 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - accuracy: 0.5834 - loss: 1.0192 - val_accuracy: 0.6936 - val_loss: 0.7018
Epoch 2/30
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7494 - loss: 0.5994 - val_accuracy: 0.7254 - val_loss: 0.6316
Epoch 3/30
44/44 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.7664 - loss: 0.5523 - val_accuracy: 0.7457 - val_loss: 0.5717
Epoch 4/30
44/44 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.7719 - loss: 0.5071 - val_accuracy: 0.7341 - val_loss: 0.5398
Epoch 5/30
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7834 - loss: 0.4841 - val_accuracy: 0.7370 - val_loss: 0.5271
Epoch 6/30
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7823 - loss: 0.4697 - val_accuracy: 0.7861 - val_loss: 0.4684
Epoch 7/30
44/44 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.8036 - loss: 0.4401 - val_accuracy: 0.7659 - val_loss: 0.4347
Epoch 8/30
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7922 - loss: 0.4551 - val_accuracy: 0.7861 - val_l

In [37]:
# 정오분류표
print(classification_report(y_test_class,y_pred_class))
print(confusion_matrix(y_test_class,y_pred_class))

              precision    recall  f1-score   support

           0       0.68      0.68      0.68        77
           1       0.58      0.50      0.54        14
           2       0.91      0.97      0.94       239
           3       1.00      0.12      0.22        16

    accuracy                           0.85       346
   macro avg       0.79      0.57      0.59       346
weighted avg       0.85      0.85      0.83       346

[[ 52   3  22   0]
 [  7   7   0   0]
 [  6   0 233   0]
 [ 12   2   0   2]]


## **3. 전복데이터 회귀**

In [133]:
df3 = pd.read_csv("C:/Users/samsung-user/OneDrive/바탕 화면/인공지능개론/5주차/abalone.csv")

In [134]:
df3.head()

id Sex  Length  Diameter  Height  Whole_weight  Shucked_weight  \
0   0   M   0.455     0.365   0.095        0.5140          0.2245   
1   1   M   0.350     0.265   0.090        0.2255          0.0995   
2   2   F   0.530     0.420   0.135        0.6770          0.2565   
3   3   M   0.440     0.365   0.125        0.5160          0.2155   
4   4   I   0.330     0.255   0.080        0.2050          0.0895   

   Viscera_weight  Shell_weight  Rings  
0          0.1010         0.150     15  
1          0.0485         0.070      7  
2          0.1415         0.210      9  
3          0.1140         0.155     10  
4          0.0395         0.055      7

In [135]:
# 타겟 : Rings(전복 나이)
X=df3.drop('Rings',axis=1)
X.head()

id Sex  Length  Diameter  Height  Whole_weight  Shucked_weight  \
0   0   M   0.455     0.365   0.095        0.5140          0.2245   
1   1   M   0.350     0.265   0.090        0.2255          0.0995   
2   2   F   0.530     0.420   0.135        0.6770          0.2565   
3   3   M   0.440     0.365   0.125        0.5160          0.2155   
4   4   I   0.330     0.255   0.080        0.2050          0.0895   

   Viscera_weight  Shell_weight  
0          0.1010         0.150  
1          0.0485         0.070  
2          0.1415         0.210  
3          0.1140         0.155  
4          0.0395         0.055

In [136]:
X = pd.get_dummies(X).values

In [137]:
y = df3['Rings'].values

In [138]:
X

array([[0, 0.455, 0.365, ..., False, False, True],
       [1, 0.35, 0.265, ..., False, False, True],
       [2, 0.53, 0.42, ..., True, False, False],
       ...,
       [4174, 0.6, 0.475, ..., False, False, True],
       [4175, 0.625, 0.485, ..., True, False, False],
       [4176, 0.71, 0.555, ..., False, False, True]], dtype=object)

In [139]:
Y

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [140]:
# 훈련/테스트 세트 분리
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [141]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((3341, 11), (836, 11), (3341,), (836,))

In [145]:
# 데이터 타입 실수형 변환
X_train = X_train.astype(np.float32)
X_test = X_test.astype(np.float32)
y_train = y_train.astype(np.float32)
y_test = y_test.astype(np.float32)

In [146]:
# 모델 정의
model = Sequential()
model.add(Input(shape=(X.shape[1],)))  # <- get_dummies 후 컬럼 수에 맞춤
model.add(Dense(16, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(16, activation='relu'))
model.add(Dense(1))  # 예측값: 나이(실수)
model.compile(optimizer='rmsprop', loss='mse', metrics=['mse'])

In [152]:
# 모델 학습
model_history = model.fit(x=X_train, y=y_train, epochs=20, batch_size=32, validation_split=0.1)
y_pred = model.predict(X_test)

Epoch 1/20
94/94 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 11.8573 - mse: 11.8573 - val_loss: 9.3470 - val_mse: 9.3470
Epoch 2/20
94/94 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 11.6993 - mse: 11.6993 - val_loss: 14.4872 - val_mse: 14.4872
Epoch 3/20
94/94 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 11.1556 - mse: 11.1556 - val_loss: 9.5423 - val_mse: 9.5423
Epoch 4/20
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 11.5425 - mse: 11.5425 - val_loss: 132.1855 - val_mse: 132.1855
Epoch 5/20
94/94 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 17.5784 - mse: 17.5784 - val_loss: 14.3269 - val_mse: 14.3269
Epoch 6/20
94/94 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 15.3660 - mse: 15.3660 - val_loss: 19.2647 - val_mse: 19.2647
Epoch 7/20
94/94 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 11.3696 - mse: 11.3696 - val_loss: 9.5700 - val_mse: 9.5700
Epoch 8/20
94/94 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 11.4503 - mse: 11.4503 - val_loss: 13.0627 - val_mse: 13.0627
Epoch 9/20
94/94 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms

In [153]:
# 모델 평가
model.evaluate(X_test, y_test)

MSE: 18.16804
